twitter:
    consumerKey:    '344eNCy2x2vqHGQrc42mCU2Pq'
    consumerSecret: 'HwtiAg8i3x09PKEZJ4sGR55CKyN4LIIw5pIkgWQrvT8DgnaaWw'
    token:          '1265126453299077125-YIXylvHC0AFEFaGMswsUJYMHrU1kOg'
    tokenSecret:    'auF4PwtrtSyWj2SQOqQCj8OWHZeD4DGH9vVM89u6wUylA'

directory:          '/media/max/Seagate Expansion Drive/Lucky Star/PrettySubtitles'
altVidDirectory:    '/media/max/Seagate Expansion Drive/Lucky Star/PrettySubtitles'
fileEnding:         '.mkv'

save:               no
saveDirectory:
    images:         '/home/max/Videos/LuckyStarTests'
    clips:          '/home/max/Videos/LuckyStarTests'

screenshot:
    imageCount:     1
    secondsApart:   0
    
clip:
    clipCount:      1
    secondsApart:   0
    clipLength:     5
    forceSubTrack:  1

chance:
    clip:           0.2
    subtitle:       .5
