twitter:
    consumerKey:    'exampleexampleexampleexampleexampleexampleexampleexample'
    consumerSecret: 'exampleexampleexampleexampleexampleexampleexample'
    token:          'exampleexampleexample-exampleexampleexampleexample'
    tokenSecret:    'exampleexampleexampleexampleexampleexample'

directory:          '/media/max/Seagate Expansion Drive/Lucky Star/PrettySubtitles'
altVidDirectory:    '/media/max/Seagate Expansion Drive/Lucky Star/PrettySubtitles'
fileEnding:         '.mkv'

save:               no
saveDirectory:
    images:         '/home/max/Videos/LuckyStarTests'
    clips:          '/home/max/Videos/LuckyStarTests'

screenshot:
    imageCount:     1
    secondsApart:   0
    
clip:
    clipCount:      1
    secondsApart:   0
    clipLength:     5
    forceSubTrack:  1

chance:
    clip:           0.2
    subtitle:       .5
